### PR TITLE
Remove ZrtpFortuna, use SecureRandom instead

### PR DESCRIPTION
**Pull request by champtar**
this need to be merged after https://github.com/jitsi/libjitsi/pull/113

### CODE REVIEW

**Comment by ibauersachs** [comment]
Not merging this, as it would create an even bigger fork in Jitsi. Consider creating a PR at https://github.com/wernerd/ZRTP4J.

**Comment by champtar** [comment]
I've open https://github.com/wernerd/ZRTP4J/pull/5

**Comment by champtar** [comment]
@ibauersachs can you reconsider this PR?
we are in an unsecure state since https://github.com/jitsi/libjitsi/pull/113
and @wernerd doesn't really want to merge https://github.com/wernerd/ZRTP4J/pull/5

**Comment by ibauersachs** [comment]
No. If there's going to be a fork, then it's going to be one that removes all the other crap too (BigInteger, array nullings, bccontrib). Feel free to start that in your own repo and I'll consider replacing the entire lib.

**Comment by champtar** [comment]
@ibauersachs 
I'm talking about fixing a security issue, you're talking about code maintenance ...

**Pull request closed without merging**
