### PR TITLE
Update bouncycastle from 1.48 to 1.64

### PR DESCRIPTION
**Pull request by annatindall**

### CODE REVIEW

**Comment by damencho** [comment]
Have you tested this change incorporated with libjitsi and in Jitsi Desktop? Do calls succeed with and without zrtp, sip and xmpp?

**Comment by annatindall** [comment]
Thanks for your quick response! We've tested sip calls both with and without zrtp using our application, which was originally forked from Jitsi Desktop. To get this change to work with Jitsi Desktop, you'd need to update its version of BouncyCastle as well.
I don't quite understand what xmpp testing you're referring to - please could you clarify?

**Comment by damencho** [comment]
Xmpp audio/video calls. But if sip srtp calls work should be ok...

**Comment by annatindall** [comment]
As far as I know, we don't support xmpp audio/video calls so that would be difficult for us to test.

**Comment by Neustradamus** [comment]
@annatindall: Thanks a lot for your https://github.com/jitsi/zrtp4j/pull/3
But can you change to 1.65?

A lot of other tickets about Bouncy Castle:
- https://github.com/jitsi/jitsi/issues/562
- https://github.com/jitsi/jitsi/pull/564
- https://github.com/jitsi/bccontrib/pull/3
- https://github.com/jitsi/jitsi-srtp/pull/13
- https://github.com/jitsi/libjitsi/pull/522
- https://github.com/jitsi/jitsi-media-transform/pull/253
- https://github.com/jitsi/jigasi/pull/259
- https://github.com/jitsi/otr4j/pull/32
- https://github.com/jitsi/jitsi-hammer/issues/36

- https://github.com/search?p=1&q=org%3Ajitsi+Bouncy+Castle&type=Issues

**Comment by annatindall** [comment]
@Neustradamus Sorry, we don't have the testing budget to upgrade to 1.65 right now, but will take a look next time we update dependent libraries if ibauersachs doesn't get there first

**Comment by Neustradamus** [comment]
@annatindall: Yes in first, it is possible to merge for 1.64 :)
@damencho, @ibauersachs: What do you think?

**Comment by Neustradamus** [comment]
@ibauersachs: Solved?

**Comment by ibauersachs** [comment]
https://github.com/jitsi/zrtp4j/blob/master/pom.xml#L37

**Comment by Neustradamus** [comment]
@ibauersachs: Thanks a lot, Jitsi project progress!

It was not specified in this ticket: Closed and solved by @ibauersachs in https://github.com/jitsi/zrtp4j/commit/bcf44f0f38088aa9b21345c63b0dff0efdef9c7f#diff-600376dffeb79835ede4a0b285078036.

**Pull request closed without merging**
